services:


  frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: astro
    ports:
      - "8081:8081"
    env_file:
      - .env
    networks:
      - design-kit-network
    

networks:
  design-kit-network:
    driver: bridge
